# let's have a look at vgsc snps
- look at gamb_colu and arab separately

### setup

In [20]:
import malariagen_data
import pandas as pd
import numpy as np
import bokeh.plotting as bkplt
import bokeh.models as bkmod
import bokeh.layouts as bklay
from bokeh.layouts import column
import bokeh.io as bkio

In [2]:
ag3 = malariagen_data.Ag3("simplecache::gs://vo_agam_release/", 
                          simplecache=dict(cache_storage="gcs_cache"))

In [3]:
#the transcript we have used previously for vgsc
vgsc = "AGAP004707-RD"


### gamb_colu

In [4]:
# get snp effects for gamb_colu
veff_gc_df = ag3.snp_effects(transcript=vgsc, site_mask='gamb_colu')

In [5]:
# meta data
metadata_df = ag3.sample_metadata(sample_sets="v3_wild")
metadata_df.columns

Index(['sample_id', 'partner_sample_id', 'contributor', 'country', 'location',
       'year', 'month', 'latitude', 'longitude', 'sex_call', 'sample_set',
       'release', 'aim_fraction_colu', 'aim_fraction_arab',
       'species_gambcolu_arabiensis', 'species_gambiae_coluzzii', 'species'],
      dtype='object')

In [6]:
# define populations
metadata_df.country.unique()

array(['Angola', 'Burkina Faso', 'Democratic Republic of Congo',
       'Central African Republic', "Cote d'Ivoire", 'Cameroon', 'Mayotte',
       'Gabon', 'Ghana', 'Gambia, The', 'Guinea', 'Mali',
       'Equatorial Guinea', 'Guinea-Bissau', 'Kenya', 'Malawi',
       'Mozambique', 'Tanzania', 'Uganda'], dtype=object)

In [7]:
# look at unique country+species counts - this will be our initial resolution
# drop arabiensis and pops smaller than 20
uni_df = metadata_df[['country', 'species', 'year']].groupby(['country','species']).count()
uni_df.reset_index(inplace=True)
uni_df = uni_df[uni_df['species'].map(lambda x: str(x)!="arabiensis")]
uni_df = uni_df[uni_df['year'].map(lambda x: x >= 20)]
len(uni_df), uni_df

(25,
                          country                        species  year
 0                         Angola                       coluzzii    81
 2                   Burkina Faso                       coluzzii   135
 3                   Burkina Faso                        gambiae   157
 6                       Cameroon                       coluzzii    26
 7                       Cameroon                        gambiae   416
 9       Central African Republic                        gambiae    55
 10                 Cote d'Ivoire                       coluzzii    80
 11  Democratic Republic of Congo                        gambiae    76
 13                         Gabon                        gambiae    69
 14                   Gambia, The                       coluzzii   169
 15                   Gambia, The                        gambiae    69
 16                   Gambia, The  intermediate_gambiae_coluzzii    41
 17                         Ghana                       coluzzii    64
 18                         Ghana                        gambiae    36
 20                        Guinea                        gambiae   123
 22                 Guinea-Bissau                        gambiae    29
 23                 Guinea-Bissau  intermediate_gambiae_coluzzii    72
 25                         Kenya                        gambiae    28
 26                         Kenya  intermediate_gambiae_coluzzii    45
 29                          Mali                       coluzzii    91
 30                          Mali                        gambiae   131
 32                       Mayotte                        gambiae    23
 33                    Mozambique                        gambiae    74
 35                      Tanzania                        gambiae    68
 38                        Uganda                        gambiae   207)

In [8]:
#build dictionary
populations_gc = {c+"_"+s: "country == '''"+c+"''' and species == '"+s+"'" for (c,s) in zip(list(uni_df.country), list(uni_df.species))}

In [9]:
populations_gc

{'Angola_coluzzii': "country == '''Angola''' and species == 'coluzzii'",
 'Burkina Faso_coluzzii': "country == '''Burkina Faso''' and species == 'coluzzii'",
 'Burkina Faso_gambiae': "country == '''Burkina Faso''' and species == 'gambiae'",
 'Cameroon_coluzzii': "country == '''Cameroon''' and species == 'coluzzii'",
 'Cameroon_gambiae': "country == '''Cameroon''' and species == 'gambiae'",
 'Central African Republic_gambiae': "country == '''Central African Republic''' and species == 'gambiae'",
 "Cote d'Ivoire_coluzzii": "country == '''Cote d'Ivoire''' and species == 'coluzzii'",
 'Democratic Republic of Congo_gambiae': "country == '''Democratic Republic of Congo''' and species == 'gambiae'",
 'Gabon_gambiae': "country == '''Gabon''' and species == 'gambiae'",
 'Gambia, The_coluzzii': "country == '''Gambia, The''' and species == 'coluzzii'",
 'Gambia, The_gambiae': "country == '''Gambia, The''' and species == 'gambiae'",
 'Gambia, The_intermediate_gambiae_coluzzii': "country == '''Gambia, The''' and species == 'intermediate_gambiae_coluzzii'",
 'Ghana_coluzzii': "country == '''Ghana''' and species == 'coluzzii'",
 'Ghana_gambiae': "country == '''Ghana''' and species == 'gambiae'",
 'Guinea_gambiae': "country == '''Guinea''' and species == 'gambiae'",
 'Guinea-Bissau_gambiae': "country == '''Guinea-Bissau''' and species == 'gambiae'",
 'Guinea-Bissau_intermediate_gambiae_coluzzii': "country == '''Guinea-Bissau''' and species == 'intermediate_gambiae_coluzzii'",
 'Kenya_gambiae': "country == '''Kenya''' and species == 'gambiae'",
 'Kenya_intermediate_gambiae_coluzzii': "country == '''Kenya''' and species == 'intermediate_gambiae_coluzzii'",
 'Mali_coluzzii': "country == '''Mali''' and species == 'coluzzii'",
 'Mali_gambiae': "country == '''Mali''' and species == 'gambiae'",
 'Mayotte_gambiae': "country == '''Mayotte''' and species == 'gambiae'",
 'Mozambique_gambiae': "country == '''Mozambique''' and species == 'gambiae'",
 'Tanzania_gambiae': "country == '''Tanzania''' and species == 'gambiae'",
 'Uganda_gambiae': "country == '''Uganda''' and species == 'gambiae'"}

In [10]:
#get allele freqs
allele_freq_df = ag3.snp_allele_frequencies(transcript=vgsc, 
                           populations=populations_gc, 
                           site_mask="gamb_colu")

In [11]:
#merge our two dfs
merged_df = pd.merge(veff_gc_df, allele_freq_df, on=['position', 'ref_allele', 'alt_allele'])

In [12]:
merged_df

,position,ref_allele,alt_allele,effect,impact,ref_codon,alt_codon,aa_pos,ref_aa,alt_aa,...,Guinea-Bissau_intermediate_gambiae_coluzzii,Kenya_gambiae,Kenya_intermediate_gambiae_coluzzii,Mali_coluzzii,Mali_gambiae,Mayotte_gambiae,Mozambique_gambiae,Tanzania_gambiae,Uganda_gambiae,maximum
0,2358161,A,G,NON_SYNONYMOUS_CODING,MODERATE,Acc,Gcc,2.0,T,A,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.004065
1,2358163,C,G,SYNONYMOUS_CODING,LOW,acC,acG,2.0,T,T,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.019231
2,2358164,G,A,NON_SYNONYMOUS_CODING,MODERATE,Gaa,Aaa,3.0,E,K,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.006579
3,2358168,A,T,NON_SYNONYMOUS_CODING,MODERATE,gAc,gTc,4.0,D,V,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.001202
4,2358168,A,G,NON_SYNONYMOUS_CODING,MODERATE,gAc,gGc,4.0,D,G,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.001202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14117,2431601,G,A,NON_SYNONYMOUS_CODING,MODERATE,cGa,cAa,2114.0,R,Q,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.017241
14118,2431601,G,T,NON_SYNONYMOUS_CODING,MODERATE,cGa,cTa,2114.0,R,L,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.002415,0.002415
14119,2431609,G,T,NON_SYNONYMOUS_CODING,MODERATE,Gat,Tat,2117.0,D,Y,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.027027,0.0,0.000000,0.027027
14120,2431613,T,C,NON_SYNONYMOUS_CODING,MODERATE,gTc,gCc,2118.0,V,A,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.006173
14121,2431614,C,T,SYNONYMOUS_CODING,LOW,gtC,gtT,2118.0,V,V,...,0.006944,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.006944

In [15]:
# filter
filter_df  = merged_df[(merged_df.impact == "HIGH") | (merged_df.impact == "MODERATE" )].copy()
freq_filtered_df = filter_df[filter_df.maximum > 0].copy()

In [16]:
# plotting stuff
freq_filtered_df['pos_Mbp'] = freq_filtered_df.position/1e6

In [30]:
geneset = ag3.geneset()

In [31]:
geneset

,seqid,source,type,start,stop,score,strand,phase,feature_id,parent_id,Name
0,2L,VectorBase,chromosome,1,49364325,NaN,NaN,NaN,2L,NaN,NaN
1,2L,VectorBase,gene,157348,186936,NaN,-,NaN,AGAP004677,NaN,NaN
2,2L,VectorBase,mRNA,157348,181305,NaN,-,NaN,AGAP004677-RA,AGAP004677,NaN
3,2L,VectorBase,three_prime_UTR,157348,157495,NaN,-,NaN,NaN,AGAP004677-RA,NaN
4,2L,VectorBase,exon,157348,157623,NaN,-,NaN,NaN,AGAP004677-RA,AGAP004677-RB-E4
...,...,...,...,...,...,...,...,...,...,...,...
196140,Y_unplaced,VectorBase,five_prime_UTR,47932,48111,NaN,+,NaN,NaN,AGAP029375-RA,NaN
196141,Y_unplaced,VectorBase,exon,47932,48138,NaN,+,NaN,NaN,AGAP029375-RA,AGAP029375-RA-E2
196142,Y_unplaced,VectorBase,CDS,48112,48138,NaN,+,0.0,AGAP029375-PA,AGAP029375-RA,NaN
196143,Y_unplaced,VectorBase,exon,48301,48385,NaN,+,NaN,NaN,AGAP029375-RA,AGAP029375-RA-E3
196144,Y_unplaced,VectorBase,CDS,48301,48385,NaN,+,0.0,AGAP029375-PA,AGAP029375-RA,NaN

In [57]:
def plot_transcript_variation(freq_df, transcript, populations, width=800, height=400):

    # SCATTER
    # tooltips
    tooltips1 = [
        ("population", '@population'),
        ("frequency", '@frequency'),
        ("position", '@position'),
        ("aa change", '@aa_change'),
    ]

    fig1 = bkplt.figure(
        title=f'Transcript - {transcript}',
        tools='xpan,xzoom_in,xzoom_out,xwheel_zoom,reset,hover',
        active_scroll='xwheel_zoom',
        active_drag='xpan',
        plot_width=width, 
        plot_height=height, 
        tooltips=tooltips1,
        toolbar_location="above")

    for pop in populations:
        df = freq_df.copy()
        df['frequency'] = df[pop]
        df['population'] = pop
        fig1.circle("pos_Mbp", 
                    pop, size=10,  
                    alpha=0.8, 
                    source=df,
                    legend_label=pop)

    fig1.yaxis.axis_label = f'population nucleotide frequency'
    fig1.xaxis.visible = False
#     fig1.legend.location = "top_left"
    fig1.add_layout(fig1.legend[0], 'right')
    fig1.legend.click_policy="hide"
    
    # GENE MODEL
    df_geneset = ag3.geneset()
    df_transcripts = df_geneset.query(f"feature_id == '{transcript}'")

    # define tooltips for hover
    tooltips2 = [
        ("Type", '@type'),
        ("Location", '@seqid:@start{,}..@stop{,}'),
    ]

    # make a figure
    fig2 = bkplt.figure(   
        plot_width=width, 
        plot_height=int(height / 4),
        tools='xpan,xzoom_in,xzoom_out,xwheel_zoom,reset,hover',
        #toolbar_location='above',
        active_scroll='xwheel_zoom',
        active_drag='xpan',
        tooltips=tooltips2,
        x_range=fig1.x_range,
    )

    # plot the transcripts


    data = df_geneset.query(f"parent_id == '{transcript}'").copy()
    data['left'] = data['start'] / 1e6  # plot in Mbp coordinates
    data['right'] = data['stop'] / 1e6  # plot in Mbp coordinates
    data['bottom'] = 0 - 0.4
    data['top'] = 0 + 0.4

    # plot exons
    exons = data.query("type == 'exon'")
    fig2.quad(bottom='bottom', 
              top='top', 
              left='left', 
              right='right',
              source=exons, 
              fill_color=None, 
              line_color='black', 
              line_width=.5, 
              fill_alpha=0)

    # plot introns
    for l, r in zip(exons[:-1]['right'], exons[1:]['left']):
        m = (l + r) / 2
        fig2.line([l, m, r], [0, 0 +.1, 0], line_width=1, line_color="black")

    # plot UTRs
    fig2.quad(bottom='bottom', top='top', left='left', right='right',
             source=data.query("type == 'five_prime_UTR'"), 
             fill_color='green', line_width=0, fill_alpha=.5)
    fig2.quad(bottom='bottom', top='top', left='left', right='right',
             source=data.query("type == 'three_prime_UTR'"), 
             fill_color='red', line_width=0, fill_alpha=.5)

    # plot CDSs
    fig2.quad(bottom='bottom', top='top', left='left', right='right',
             source=data.query("type == 'CDS'"), 
             fill_color='blue', line_width=0, fill_alpha=.5)

    fig2.xaxis.axis_label = f'Position (Mbp)'
    fig2.y_range = bkmod.Range1d(-.5, len(df_transcripts)-.5)
    fig2.xaxis.axis_label = f'Contig {df_transcripts.seqid.item()} position (Mbp)'
#     yticks = list(range(len(df_transcripts)))
#     yticklabels = df_transcripts.index
#     fig2.yaxis.ticker = yticks
#     fig2.yaxis.major_label_overrides = {k: v for k, v in zip(yticks, yticklabels)}
    fig2.toolbar.logo = None 
    fig2.toolbar_location = None

    bkplt.show(column(fig1, fig2))

In [58]:
plot_transcript_variation(freq_df=freq_filtered_df, transcript=vgsc, populations=populations_gc)

In [ ]:
# todo - fix ytick brokeness and add plot into notebook
# - we will need colours for each pop...JOY